2009-08-12T11:36:00.000Z	staminna		morning: I have broken packages apt-get clean && sudo apt-get check don't fix
2009-08-12T11:37:00.000Z	ActionParsnip	staminna	can you please pastebin the output of: sudo apt-get update; sudo apt-get -f install; sudo apt-get upgrade
2009-08-12T11:43:00.000Z	staminna	ActionParsnip	http://pastebin.com/m64f8963a
2009-08-12T11:44:00.000Z	ActionParsnip	staminna	ok looks like you will need to create some files
2009-08-12T11:44:00.000Z	ActionParsnip	staminna	all the files it says are missing, use those filenames with touch
2009-08-12T11:44:00.000Z	staminna	ActionParsnip	It's not overriding the local build ( I didn't know this package exist) I think it's symlinking glue
2009-08-12T11:44:00.000Z	ActionParsnip	staminna	e.g. touch /usr/lib/python2.6/dist-packages/mapnik/__init__.py
2009-08-12T11:45:00.000Z	ActionParsnip	staminna	once you recreate those files you should then be able to remove it
2009-08-12T11:45:00.000Z	staminna	ActionParsnip	Done the touch, no output
2009-08-12T11:46:00.000Z	ActionParsnip	staminna	you won't
2009-08-12T11:46:00.000Z	ActionParsnip	staminna	now do the other file names in your output
2009-08-12T11:46:00.000Z	staminna	ActionParsnip	ok 1 minute
2009-08-12T11:46:00.000Z	ActionParsnip	staminna	in linux you dont get a nice "ok" as its a waste of time
2009-08-12T11:46:00.000Z	ActionParsnip	staminna	no news is good news
2009-08-12T11:50:00.000Z	staminna	ActionParsnip	I've done that for all
2009-08-12T11:52:00.000Z	staminna	ActionParsnip	Redo sudo apt-get -f install; sudo apt-get upgrade ?
2009-08-12T11:52:00.000Z	ActionParsnip	staminna	after creating those files, yes
2009-08-12T11:53:00.000Z	staminna	ActionParsnip	Same output, same issue: dpkg: error processing python-mapnik (--configure):
2009-08-12T11:54:00.000Z	ActionParsnip	staminna	same error about the files?
2009-08-12T11:54:00.000Z	staminna	ActionParsnip	Yes, exactly the same output
2009-08-12T11:55:00.000Z	ActionParsnip	staminna	sounds like a bug.
2009-08-12T12:04:00.000Z	staminna	ActionParsnip	while trying to compile the package from subversion svn, the python test run fails because of some bad symlinking, the mapnik.org wiki says it may be Boost version is not compatible with the Mapnik release version, in such case, the how-to fix link is empty.
