2012-08-26T20:02:00.000Z	lidar	py_can	disable passive ftp
2012-08-26T20:02:00.000Z	py_can	lidar	ok, sec
2012-08-26T20:03:00.000Z	py_can	lidar	there is no passive configuration in my vsftpd.conf
2012-08-26T20:04:00.000Z	py_can	lidar	http://pastebin.com/5x330yg4 Here is my config
2012-08-26T20:07:00.000Z	lidar	py_can	add pasv_enable=no
2012-08-26T20:08:00.000Z	py_can	lidar	looks like that worked. Now i'm getting 500 permission denied errors. Let's see what that's about..
2012-08-26T20:08:00.000Z	lidar	py_can	hosts is not the problem .. it may be the issue on the remote side if your trying to connect to a hostname
2012-08-26T20:08:00.000Z	py_can	lidar	i am using a hostname, yes
2012-08-26T20:10:00.000Z	lidar	py_can	if the hostname resolves to the proper ip address then the hosts file doesnt matter
2012-08-26T20:10:00.000Z	py_can	lidar	ok
2012-08-26T20:11:00.000Z	lidar	py_can	also your router might./should be blocking your connection unless you have a seperate connection on the outside for testing
2012-08-26T20:14:00.000Z	py_can	lidar	any clue? :D
2012-08-26T20:22:00.000Z	lidar	py_can	http://forums.opensuse.org/english/get-technical-help-here/network-internet/466059-vsftp-not-allowing-external-connections.html check this out
2012-08-26T20:22:00.000Z	py_can	lidar	thajnks
2012-08-26T20:23:00.000Z	lidar	py_can	scroll that down a bit heposted a solution
2012-08-26T20:23:00.000Z	py_can	lidar	ok!
2012-08-26T20:24:00.000Z	py_can	lidar	but when I enable passive mode, I get the "server responded with a bad routable address"
2012-08-26T20:24:00.000Z	py_can	lidar	the solution makes me enable passive, which i know doenst work
2012-08-26T20:25:00.000Z	py_can	lidar	ok
2012-08-26T20:25:00.000Z	py_can	lidar	trying now
2012-08-26T20:25:00.000Z	lidar	py_can	only need to assighn like 3 ports for testing
2012-08-26T20:36:00.000Z	py_can	lidar	It works! Love you!
